version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest 
    container_name: vaultwarden
    expose:
      - "80"
      - "3012"
    volumes:
      - ./data/bitwarden:/data
    restart: on-failure
    environment:
      WEBSOCKET_ENABLED: 'true'
 
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: always
    networks:
        qnet-static:
            ipv4_address: 192.168.2.153
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx
      - ./data/ssl:/etc/ssl

  bw_backup:
    image: bruceforce/vaultwarden-backup:latest
    container_name: vaultwarden-backup
    restart: on-failure
    depends_on:
      - bitwarden
    volumes:
      - ./data/bitwarden:/data
      - /opt/Bitwarden-Backup:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_FILE=/data/db.sqlite3
      - BACKUP_FILE=/backup/backup.sqlite3
      - BACKUP_FILE_PERMISSIONS=700
      - CRON_TIME=0 1 * * *
      - TIMESTAMP=false
      - UID=0
      - GID=0

networks:
    qnet-static:
        driver: qnet
        driver_opts:
            iface: "eth0"
        ipam:
          driver: qnet
          options:
            iface: "eth0"
          config:
            - subnet: 192.168.2.0/24
              gateway: 192.168.2.1
